version: '3.7'

services:
  web:
    container_name: react_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: "local"
      REACT_APP_API_KEY: ""