apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  name: "<PROJECT_SERVICE>"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      timeoutSeconds: 300
      containers:
        - image: <CONTAINER_IMAGE>
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
            - name: GOOGLE_CLOUD_PROJECT
              value: "<GOOGLE_CLOUD_PROJECT>"
            - name: REACT_APP_API_KEY
              value: "<REACT_APP_API_KEY>"
  traffic:
    - latestRevision: true
      percent: 100